eureka:
  instance:
    prefer-ip-address: false
    # 1. Disable the HTTP port in the registry
  #   non-secure-port-enabled: false
  #   secure-port-enabled: true
  #   secure-port: ${server.port}
    
  #   # 2. Force the registration to use the domain name, not the IP
  #   hostname: docmaccdentalclinic.local
  #   prefer-ip-address: false

  #   # 3. Explicitly set absolute HTTPS URLs (Crucial for the dashboard and Gateway)
  #   status-page-url: https://${eureka.instance.hostname}:${server.port}/actuator/info
  #   health-check-url: https://${eureka.instance.hostname}:${server.port}/actuator/health
  #   home-page-url: https://${eureka.instance.hostname}:${server.port}/
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:https://docmaccdentalclinic.local:8761/eureka}

spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411 # docker desktop
    # baseUrl: http://localhost:9411 # local machine

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans # docker desktop
      # endpoint: http://localhost:9411/api/v2/spans # local machine

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
